//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int playerId1 { get; set; }
        public int playerId2 { get; set; }
        public string tipo { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
