//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.PlayersByGame = new HashSet<PlayersByGame>();
        }
    
        public int gameId { get; set; }
        public string invitationCode { get; set; }
        public string gameStatus { get; set; }
        public Nullable<int> numberPlayers { get; set; }
        public Nullable<int> timePerTurn { get; set; }
        public Nullable<int> lives { get; set; }
        public Nullable<int> winnerPlayerId { get; set; }
        public int hostPlayerId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayersByGame> PlayersByGame { get; set; }
    }
}
