//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamExplotionDBEntities : DbContext
    {
        public ExamExplotionDBEntities()
            : base("name=ExamExplotionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessory { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayersByGame> PlayersByGame { get; set; }
        public virtual DbSet<PurchasedAccessory> PurchasedAccessory { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
