//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamExplotionDBEntities : DbContext
    {
        public ExamExplotionDBEntities()
            : base("name=ExamExplotionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessory { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayersByGame> PlayersByGame { get; set; }
        public virtual DbSet<PurchasedAccessory> PurchasedAccessory { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<BlockList> BlockList { get; set; }
    }
}
