//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedAccessory
    {
        public int playerId { get; set; }
        public int accessoryId { get; set; }
        public Nullable<bool> inUse { get; set; }
        public int PurchasedAccessoryId { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Player Player { get; set; }
    }
}
