//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int idPlayerReported { get; set; }
        public int amount { get; set; }
<<<<<<< HEAD
=======
        public int reportId { get; set; }
>>>>>>> f796509853e9a2b1f8b30832f75c8529577581bf
    
        public virtual Player Player { get; set; }
    }
}
